# Generated by Django 5.0.6 on 2024-06-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_customuser_address_customuser_age_customuser_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(null=True, upload_to='Profile_img/'),
        ),
    ]
